"""Update micro signal cells with production-accurate implementations."""
import json
from pathlib import Path

NB_PATH = Path(__file__).parent.parent / "notebooks" / "demo_signals_index_debt_equity.ipynb"

UPDATES = [
    (29, "markdown", "## S1: Single-Name Spread Mean-Reversion (Micro)"),
    (30, "code", "\n".join([
        "def compute_signal_s1_spread_reversion_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S1 Micro: Single-Name Spread Mean-Reversion',
        "",
        "    Production signal (s1_spread_reversion.py).",
        "    Source data: Constituent par spreads (CDX IG / iTraxx EU).",
        "",
        "    Logic:",
        "    1. Per constituent: z = (spread - EWM_mean) / EWM_std  [grouped by issuer_id]",
        "    2. Cross-sectional median of z across all names per date",
        "    3. Negate: wide spreads -> positive z -> expect tightening -> long credit",
        "    4. EWM z-score + tanh compression via zscore_ewm()",
        "",
        "    Routing (production):",
        "    - EU pairs (main|vg1, xover|vg1)         : iTraxx EU constituents, reversion",
        "    - BKLN/LQD pairs (bkln|rty1, lqd_rh|es1) : CDX IG - momentum (sign negated)",
        "    - All other pairs                         : CDX IG - reversion",
        "",
        "    Positive score = wide spreads -> expect tightening -> long credit.",
        '    """',
        "    alpha = get_ewm_alpha(config.half_life_hl_mean)",
        "",
        "    # Step 1: Per-constituent EWM z-score",
        '    score_per_name = df.with_columns([',
        '        pl.col("issuer_spread").ewm_mean(alpha=alpha).over("issuer_id").alias("_ewm_mean"),',
        '        pl.col("issuer_spread").ewm_std(alpha=alpha).over("issuer_id").alias("_ewm_std"),',
        "    ]).with_columns([",
        '        ((pl.col("issuer_spread") - pl.col("_ewm_mean")) / pl.col("_ewm_std")).alias("_z_score")',
        "    ])",
        "",
        "    # Step 2: Cross-sectional median per date",
        '    score_df = score_per_name.group_by("date").agg(',
        '        pl.col("_z_score").median().alias("score")',
        '    ).sort("date")',
        "",
        "    # Step 3: Negate (wide spread -> positive z -> expect tightening -> long credit)",
        '    score_df = score_df.with_columns(-pl.col("score").alias("score"))',
        "",
        "    # Step 4: EWM z-score + tanh",
        "    return score_df.pipe(",
        '        zscore_ewm, "score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s1_spread_reversion_micro",',
        '    ).drop("score")',
        "",
        "",
        'print("S1 Micro: Single-Name Spread Mean-Reversion")',
    ])),
    (31, "markdown", "## S2: Bottom-Up Equity Volatility (Micro)"),
    (32, "code", "\n".join([
        "def compute_signal_s2_equity_vol_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S2 Micro: Bottom-Up Equity Volatility',
        "",
        "    Production signal (s7_equity_vol.py).",
        "    Source data: Constituent equity returns (all 4 indices).",
        "",
        "    Logic:",
        "    1. abs(equity_return) per constituent",
        "    2. Cross-sectional median of abs(equity_return) per date -> bottom-up vol proxy",
        "    3. Negate: rising equity vol -> risk-off -> short credit",
        "    4. EWM z-score + tanh compression via zscore_ewm()",
        "",
        "    Routes to all 4 indices (CDX NA IG, CDX NA HY, iTraxx Main, iTraxx Crossover).",
        "",
        "    Positive score = calm equity markets -> long credit.",
        '    """',
        "    # Step 1+2: Cross-sectional median of |equity_return| per date",
        '    score_df = df.group_by("date").agg(',
        '        pl.col("issuer_equity_return").abs().median().alias("score")',
        '    ).sort("date")',
        "",
        "    # Step 3: Negate (high equity vol -> short credit)",
        '    score_df = score_df.with_columns(-pl.col("score").alias("score"))',
        "",
        "    # Step 4: EWM z-score + tanh",
        "    return score_df.pipe(",
        '        zscore_ewm, "score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s2_equity_vol_micro",',
        '    ).drop("score")',
        "",
        "",
        'print("S2 Micro: Bottom-Up Equity Volatility")',
    ])),
    (33, "markdown", "## S3: Distance-to-Default Momentum (Micro)"),
    (34, "code", "\n".join([
        "def compute_signal_s3_dtd_momentum_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S3 Micro: Distance-to-Default Momentum',
        "",
        "    Production signal (s2_dtd_momentum.py).",
        "    Source data: Morningstar DTD + CDX IG/HY constituents.",
        "",
        "    Logic:",
        '    1. Filter out Financial sector names (sector != "Financials")',
        "    2. Cross-sectional median of DTD levels per date",
        "    3. EWM z-score + tanh via zscore_ewm()",
        "",
        "    Universal signal: same score for all asset pairs.",
        "    Positive score = rising median DTD = improving credit fundamentals -> long credit.",
        '    """',
        "    # Step 1+2: Exclude Financials, compute cross-sectional median DTD per date",
        "    score_df = (",
        '        df.filter(pl.col("sector") != pl.lit("Financials"))',
        '        .group_by("date").agg(',
        '            pl.col("dtd").median().alias("score")',
        '        ).sort("date")',
        "    )",
        "",
        "    # Step 3: EWM z-score + tanh",
        "    return score_df.pipe(",
        '        zscore_ewm, "score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s3_dtd_momentum_micro",',
        '    ).drop("score")',
        "",
        "",
        'print("S3 Micro: Distance-to-Default Momentum")',
    ])),
    (35, "markdown", "## S4: Spread Skew Compression/Decompression -- Kalman (Micro)"),
    (36, "code", "\n".join([
        "def compute_signal_s4_spread_skew_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S4 Micro: Spread Skew Compression/Decompression (Kalman)',
        "",
        "    Production signal (s3_spread_skew_comp_decomp.py).",
        "    Source data: HY & IG constituent spreads (NA + EU).",
        "",
        "    Logic:",
        "    1. x = cross-sectional skew of IG spread pct_change per date",
        "    2. y = cross-sectional skew of HY spread pct_change per date",
        "    3. Kalman regression: y ~ beta*x + alpha  (time-varying beta)",
        "    4. residual = y - (beta*x + alpha)",
        "    5. score = cumsum(-residual)   [cumulative negated residual]",
        "    6. EWM z-score + tanh via zscore_ewm()",
        "",
        "    Routing: EU pairs -> iTraxx Crossover/Main; NA pairs -> CDX HY/IG.",
        "    Positive = HY tail risk below Kalman prediction -> compression -> long credit.",
        "    Expects df columns: date, hy_skew, ig_skew.",
        '    """',
        '    x = df["ig_skew"].to_numpy()',
        '    y = df["hy_skew"].to_numpy()',
        "",
        "    # Kalman regression: y ~ beta*x + alpha  (time-varying)",
        "    state_means = compute_kalman_beta(x, y, delta=0.01, use_constant=True)",
        "    beta  = state_means[:, 0, 0]",
        "    alpha = state_means[:, 0, 1]",
        "",
        "    residual = y - (beta * x + alpha)",
        "    score    = np.nancumsum(-residual)   # cumulative negated residual",
        "",
        '    result = df.select("date").with_columns(pl.Series("_score", score))',
        "",
        "    return result.pipe(",
        '        zscore_ewm, "_score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s4_spread_skew_micro",',
        '    ).drop("_score")',
        "",
        "",
        'print("S4 Micro: Spread Skew Compression/Decompression (Kalman)")',
    ])),
    (37, "markdown", "## S5: Spread Dispersion -- Cross-Sectional Vol (Micro)"),
    (38, "code", "\n".join([
        "def compute_signal_s5_spread_dispersion_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S5 Micro: Spread Dispersion (Cross-Sectional Volatility)',
        "",
        "    Production signal (s4_spread_dispersion.py).",
        "    Source data: HY constituent spreads (CDX HY / iTraxx Crossover).",
        "",
        "    Logic:",
        "    1. Per constituent: spread_pct_change per date  (grouped by issuer_id)",
        "    2. sign(spread_pct_change) per constituent per date",
        "    3. Cross-sectional std of sign values per date",
        "    4. EWM z-score + tanh via zscore_ewm()",
        "",
        "    Routing: EU pairs (vg1) -> iTraxx Crossover; NA pairs -> CDX HY.",
        "    Positive = high dispersion = idiosyncratic market -> long credit (not systemic stress).",
        "    Negative = low dispersion  = correlated stress -> short credit.",
        '    """',
        "    # Step 1+2: sign of spread pct_change, per constituent",
        "    df_sign = df.with_columns([",
        '        pl.col("issuer_spread").pct_change().over("issuer_id").alias("_spread_rtn")',
        "    ]).with_columns([",
        '        pl.col("_spread_rtn").sign().alias("_sign_rtn")',
        "    ])",
        "",
        "    # Step 3: Cross-sectional std of sign per date",
        '    score_df = df_sign.group_by("date").agg(',
        '        pl.col("_sign_rtn").std().alias("score")',
        '    ).sort("date")',
        "",
        "    # Step 4: EWM z-score + tanh",
        "    return score_df.pipe(",
        '        zscore_ewm, "score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s5_spread_dispersion_micro",',
        '    ).drop("score")',
        "",
        "",
        'print("S5 Micro: Spread Dispersion (Cross-Sectional Vol)")',
    ])),
    (39, "markdown", "## S6: Cash-Index Basis -- Kalman (Micro)"),
    (40, "code", "\n".join([
        "def compute_signal_s6_cash_index_basis_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S6 Micro: Cash-Index Basis -- Intrinsic vs Traded Spread (Kalman)',
        "",
        "    Production signal (s5_cash_index_basis.py).",
        "    Source data: JPM DQ index spreads + constituent mean spreads (CDX IG / iTraxx Main).",
        "",
        "    Logic:",
        "    1. x = traded index spread (CDX IG or iTraxx Main) per date",
        "    2. y = mean constituent spread across names per date  [intrinsic spread]",
        "    3. Kalman regression: y ~ beta*x + alpha  (time-varying beta)",
        "    4. residual = y - (beta*x + alpha)",
        "    5. score = cumsum(-residual)   [cumulative negated residual]",
        "    6. EWM z-score + tanh via zscore_ewm()",
        "",
        "    Routing: vg1 pairs -> iTraxx Main; all others -> CDX IG.",
        "    Positive = constituent mean below Kalman baseline -> cash cheap -> long credit.",
        "    Expects df columns: date, issuer_id, issuer_spread, cdx_spread.",
        '    """',
        "    # Step 1: Mean constituent spread per date",
        '    const_mean = df.group_by("date").agg(',
        '        pl.col("issuer_spread").mean().alias("_const_mean")',
        '    ).sort("date")',
        "",
        "    # Join traded index spread (one row per date)",
        '    idx_spread = df.select(["date", "cdx_spread"]).unique("date").sort("date")',
        '    combined   = const_mean.join(idx_spread, on="date", how="left")',
        "",
        '    x = combined["cdx_spread"].to_numpy()',
        '    y = combined["_const_mean"].to_numpy()',
        "",
        "    # Kalman regression: y ~ beta*x + alpha  (time-varying)",
        "    state_means = compute_kalman_beta(x, y, delta=0.01, use_constant=True)",
        "    beta  = state_means[:, 0, 0]",
        "    alpha = state_means[:, 0, 1]",
        "",
        "    residual = y - (beta * x + alpha)",
        "    score    = np.nancumsum(-residual)   # cumulative negated residual",
        "",
        '    result = combined.select("date").with_columns(pl.Series("_score", score))',
        "",
        "    return result.pipe(",
        '        zscore_ewm, "_score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s6_cash_index_basis_micro",',
        '    ).drop("_score")',
        "",
        "",
        'print("S6 Micro: Cash-Index Basis (Kalman)")',
    ])),
    (41, "markdown", "## S7: Options Implied Volatility -- Relative IV (Micro)"),
    (42, "code", "\n".join([
        "def compute_signal_s7_options_iv_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S7 Micro: Options Implied Volatility (Relative IV)',
        "",
        "    Production signal (s6_options_implied_vol.py).",
        "    Source data: ivy_ivol_surface_x1 (30-day IV, CDX IG/HY constituents).",
        "",
        "    Logic:",
        "    1. Per constituent: rel_iv = vol_30d / EWM_mean(vol_30d, hl=63)",
        "       [1.0 = at-trend; >1.0 = elevated]",
        "    2. Cross-sectional median of rel_iv per date",
        "    3. Negate: elevated/rising IV -> short credit",
        "    4. EWM z-score + tanh via zscore_ewm()",
        "",
        "    Limited to NA pairs (CDX IG/HY universe).",
        "    Positive score = subdued IV -> long credit.",
        "    Expects df columns: date, issuer_id, issuer_option_iv (= vol_30d).",
        '    """',
        "    alpha_63 = get_ewm_alpha(63)",
        "",
        "    # Step 1: Relative IV = vol_30d / EWM_mean(vol_30d, hl=63)  per constituent",
        "    df_rel = df.with_columns([",
        "        (",
        '            pl.col("issuer_option_iv") /',
        '            pl.col("issuer_option_iv").ewm_mean(alpha=alpha_63).over("issuer_id")',
        '        ).alias("_rel_iv")',
        "    ])",
        "",
        "    # Step 2: Cross-sectional median of rel_iv per date",
        '    score_df = df_rel.group_by("date").agg(',
        '        pl.col("_rel_iv").median().alias("score")',
        '    ).sort("date")',
        "",
        "    # Step 3: Negate (high IV -> short credit)",
        '    score_df = score_df.with_columns(-pl.col("score").alias("score"))',
        "",
        "    # Step 4: EWM z-score + tanh",
        "    return score_df.pipe(",
        '        zscore_ewm, "score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s7_options_iv_micro",',
        '    ).drop("score")',
        "",
        "",
        'print("S7 Micro: Options Implied Volatility (Relative IV)")',
    ])),
    (43, "markdown", "## S8: Spread-Equity Directional Agreement (Micro)"),
    (44, "code", "\n".join([
        "def compute_signal_s8_spread_vs_equity_micro(df: pl.DataFrame, config: SignalConfig) -> pl.DataFrame:",
        '    """S8 Micro: Spread-Equity Directional Agreement (Cross-Sectional Std)',
        "",
        "    Production signal (s0_spread_vs_equity.py).",
        "    Universal signal: same score for all asset pairs.",
        "",
        "    Logic:",
        "    1. Per constituent: sign_product = sign(spread_pct_change) * sign(equity_return)",
        "    2. Cross-sectional std of sign_product per date",
        "       Low std  = all names agree -> orderly market -> carry environment",
        "       High std = names disagree -> idiosyncratic stress",
        "    3. Negate: low std = agreement -> positive score -> long credit",
        "    4. EWM z-score + tanh via zscore_ewm()",
        "",
        "    Positive score = high directional agreement -> favours long credit carry.",
        "    Expects df columns: date, issuer_id, issuer_spread, issuer_equity_return.",
        '    """',
        "    # Step 1: sign product per constituent per date",
        "    df_signs = df.with_columns([",
        '        pl.col("issuer_spread").pct_change().over("issuer_id").alias("_spread_rtn"),',
        "    ]).with_columns([",
        "        (",
        '            pl.col("_spread_rtn").sign() * pl.col("issuer_equity_return").sign()',
        '        ).alias("_sign_product")',
        "    ])",
        "",
        "    # Step 2: Cross-sectional std of sign_product per date",
        '    score_df = df_signs.group_by("date").agg(',
        '        pl.col("_sign_product").std().alias("score")',
        '    ).sort("date")',
        "",
        "    # Step 3: Negate (low std = agreement -> positive score -> long credit)",
        '    score_df = score_df.with_columns(-pl.col("score").alias("score"))',
        "",
        "    # Step 4: EWM z-score + tanh",
        "    return score_df.pipe(",
        '        zscore_ewm, "score", config.half_life_hl_mean, config.half_life_hl_std,',
        '        "s8_spread_vs_equity_micro",',
        '    ).drop("score")',
        "",
        "",
        'print("S8 Micro: Spread-Equity Directional Agreement")',
    ])),
]


def main():
    with open(NB_PATH) as f:
        nb = json.load(f)
    cells = nb["cells"]
    for idx, cell_type, source in UPDATES:
        c = cells[idx]
        assert c["cell_type"] == cell_type, f"Cell {idx}: expected {cell_type}, got {c['cell_type']}"
        c["source"] = [source]
        if cell_type == "code":
            c["outputs"] = []
            c["execution_count"] = None
    with open(NB_PATH, "w") as f:
        json.dump(nb, f, indent=1)
    code_cells = sum(1 for _, t, _ in UPDATES if t == "code")
    md_cells   = sum(1 for _, t, _ in UPDATES if t == "markdown")
    print(f"Updated {md_cells} headings + {code_cells} code cells -> {NB_PATH}")


if __name__ == "__main__":
    main()
