from __future__ import annotations

import json
import time

import pytest


def _poll_run_terminal(client, run_id: str, timeout_s: float = 30.0) -> dict:
    t0 = time.time()
    while True:
        rr = client.get(f"/api/runs/{run_id}")
        assert rr.status_code == 200
        run = rr.json()["run"]
        st = run["status"]
        if st in ("succeeded", "failed"):
            return run
        if time.time() - t0 > timeout_s:
            raise AssertionError(f"timeout waiting for run, last={st}")
        time.sleep(0.05)


def _write_parquet_market_data(*, out_path, dates, ticker: str = "AAPL"):
    import pandas as pd

    df = pd.DataFrame(
        {
            "date": list(dates) * 1,
            "ticker": [ticker for _ in dates],
            "open": [100.0 + i for i in range(len(dates))],
            "high": [101.0 + i for i in range(len(dates))],
            "low": [99.0 + i for i in range(len(dates))],
            "close": [100.5 + i for i in range(len(dates))],
            "volume": [1_000_000 for _ in dates],
        }
    )
    df["date"] = pd.to_datetime(df["date"])
    df.to_parquet(out_path, index=False)


@pytest.mark.slow
def test_process_pool_runner_succeeds_and_writes_core_artifacts(tmp_path, monkeypatch):
    """Phase 3.5.2 success path: true backtest run in a worker process.

    Requirements:
      - run status == succeeded
      - logs.txt written
      - index.html written
      - summary.json written and contains artifacts
      - parquet artifacts include returns.parquet
      - /api/runs/{id}/summary works
      - /api/runs/{id}/artifact/{file} download works
    """

    from fastapi.testclient import TestClient

    from quantdsl_backtest.platform_api.main import create_app

    # Hermetic db
    monkeypatch.setattr(
        "quantdsl_backtest.platform_api.services.run_store_factory.default_runs_db_path",
        lambda: tmp_path / "runs.db",
    )

    # Hermetic strategies dir
    strategies_dir = tmp_path / "strategies"
    monkeypatch.setattr(
        "quantdsl_backtest.platform_api.services.strategy_discovery.default_strategies_dir",
        lambda: strategies_dir,
    )
    strategies_dir.mkdir(parents=True, exist_ok=True)

    # Tiny deterministic parquet market data
    data_path = tmp_path / "md.parquet"
    dates = ["2025-01-01", "2025-01-02", "2025-01-03", "2025-01-06", "2025-01-07"]
    _write_parquet_market_data(out_path=data_path, dates=dates, ticker="AAPL")

    # Minimal deterministic strategy using a single instrument.
    # We use a trivial ranking factor/signal to keep the DSL active.
    parquet_uri = "parquet://" + data_path.as_posix()

    import textwrap

    # NOTE: keep this snippet aligned with the current DSL `Strategy` dataclass
    # contract (factors/signals are dicts; execution/costs are required).
    src = textwrap.dedent(
        f"""
        # AUTO-GENERATED BY TEST: s_proc_ok
        from quantdsl_backtest.dsl.strategy import Strategy
        from quantdsl_backtest.dsl.data_config import DataConfig
        from quantdsl_backtest.dsl.backtest_config import BacktestConfig, Reporting
        from quantdsl_backtest.dsl.universe import Universe
        from quantdsl_backtest.dsl.portfolio import LongShortPortfolio, EqualWeight, TopN, BottomN, Book
        from quantdsl_backtest.dsl.factors import ReturnFactor
        from quantdsl_backtest.dsl.signals import CrossSectionRank
        from quantdsl_backtest.dsl.execution import Execution, OrderPolicy, LatencyModel, PowerLawSlippageModel, VolumeParticipation
        from quantdsl_backtest.dsl.costs import Costs, Commission, BorrowCost, FinancingCost, StaticFees

        factors = {{
            'mom_1': ReturnFactor(name='mom_1', field='close', lookback=1, method='simple')
        }}
        signals = {{
            'sig': CrossSectionRank(name='sig', factor_name='mom_1')
        }}

        long_book = Book(
            name='long_book',
            selector=TopN(factor_name='sig', n=1, mask_name=None),
            weighting=EqualWeight(),
        )
        short_book = Book(
            name='short_book',
            selector=BottomN(factor_name='sig', n=0, mask_name=None),
            weighting=EqualWeight(),
        )

        portfolio = LongShortPortfolio(
            long_book=long_book,
            short_book=short_book,
            rebalance_frequency='1d',
            signal_delay_bars=1,
        )

        execution = Execution(
            order_policy=OrderPolicy(),
            latency=LatencyModel(),
            slippage=PowerLawSlippageModel(base_bps=0.0, k=0.0),
            volume_limits=VolumeParticipation(max_participation=1.0),
        )
        costs = Costs(
            commission=Commission(type='bps_notional', amount=0.0),
            borrow=BorrowCost(default_annual_rate=0.0),
            financing=FinancingCost(base_rate_curve='SOFR', spread_bps=0.0),
            fees=StaticFees(nav_fee_annual=0.0, perf_fee_fraction=0.0),
        )

        strategy = Strategy(
            name='s_proc_ok',
            data=DataConfig(source=r'{parquet_uri}', calendar='XNYS', frequency='1d', start='2025-01-01', end='2025-01-07'),
            universe=Universe(name='TEST', static_instruments=['AAPL']),
            factors=factors,
            signals=signals,
            portfolio=portfolio,
            execution=execution,
            costs=costs,
            backtest=BacktestConfig(engine='event_driven', reporting=Reporting(output_dir=None)),
        )
        """
    ).lstrip()

    (strategies_dir / "s_proc_ok.py").write_text(src, encoding="utf-8")

    app = create_app()

    # Enable process pool on TaskRunner
    from quantdsl_backtest.platform_api.services.task_runner import TaskRunner

    app.state.task_runner = TaskRunner(run_store=app.state.run_store, enable_process_pool=True, max_workers=1)

    client = TestClient(app, raise_server_exceptions=False)

    r = client.post("/api/runs", json={"strategy_id": "s_proc_ok", "params": {}})
    assert r.status_code == 200
    run_id = r.json()["run_id"]

    run = _poll_run_terminal(client, run_id, timeout_s=30.0)
    assert run["status"] == "succeeded", f"run failed: {run.get('error')}"

    import pathlib

    out_dir = pathlib.Path(run["artifacts_dir"])
    assert (out_dir / "logs.txt").exists()
    assert (out_dir / "index.html").exists()
    assert (out_dir / "summary.json").exists()

    j = json.loads((out_dir / "summary.json").read_text(encoding="utf-8"))
    assert "artifacts" in j
    assert "returns.parquet" in j["artifacts"]

    # Summary endpoint should work
    rsum = client.get(f"/api/runs/{run_id}/summary")
    assert rsum.status_code == 200

    # Artifact download should work
    rx = client.get(f"/api/runs/{run_id}/artifact/returns.parquet")
    assert rx.status_code == 200
    assert len(rx.content) > 0


@pytest.mark.slow
def test_process_pool_runner_failed_run_persists_logs_and_error(tmp_path, monkeypatch):
    """Phase 3.5.2 failure path: worker should still write logs.txt and RunStore should store error."""

    from fastapi.testclient import TestClient

    from quantdsl_backtest.platform_api.main import create_app

    # Hermetic db
    monkeypatch.setattr(
        "quantdsl_backtest.platform_api.services.run_store_factory.default_runs_db_path",
        lambda: tmp_path / "runs.db",
    )

    # Hermetic strategies dir
    strategies_dir = tmp_path / "strategies"
    monkeypatch.setattr(
        "quantdsl_backtest.platform_api.services.strategy_discovery.default_strategies_dir",
        lambda: strategies_dir,
    )
    strategies_dir.mkdir(parents=True, exist_ok=True)

    # Strategy references a missing parquet file => should fail in data loader
    src = """
from quantdsl_backtest.dsl.strategy import Strategy
from quantdsl_backtest.dsl.data_config import DataConfig
from quantdsl_backtest.dsl.backtest_config import BacktestConfig, Reporting
from quantdsl_backtest.dsl.universe import Universe
from quantdsl_backtest.dsl.portfolio import LongShortPortfolio, EqualWeight, TopN, BottomN, Book
from quantdsl_backtest.dsl.factors import ReturnFactor
from quantdsl_backtest.dsl.signals import CrossSectionRank
from quantdsl_backtest.dsl.execution import Execution, OrderPolicy, LatencyModel, PowerLawSlippageModel, VolumeParticipation
from quantdsl_backtest.dsl.costs import Costs, Commission, BorrowCost, FinancingCost, StaticFees

factors = {
    'mom_1': ReturnFactor(name='mom_1', field='close', lookback=1, method='simple')
}
signals = {
    'sig': CrossSectionRank(name='sig', factor_name='mom_1')
}

long_book = Book(
    name='long_book',
    selector=TopN(factor_name='sig', n=1, mask_name=None),
    weighting=EqualWeight(),
)
short_book = Book(
    name='short_book',
    selector=BottomN(factor_name='sig', n=0, mask_name=None),
    weighting=EqualWeight(),
)
portfolio = LongShortPortfolio(
    long_book=long_book,
    short_book=short_book,
    rebalance_frequency='1d',
    signal_delay_bars=1,
)

execution = Execution(
    order_policy=OrderPolicy(),
    latency=LatencyModel(),
    slippage=PowerLawSlippageModel(base_bps=0.0, k=0.0),
    volume_limits=VolumeParticipation(max_participation=1.0),
)
costs = Costs(
    commission=Commission(type='bps_notional', amount=0.0),
    borrow=BorrowCost(default_annual_rate=0.0),
    financing=FinancingCost(base_rate_curve='SOFR', spread_bps=0.0),
    fees=StaticFees(nav_fee_annual=0.0, perf_fee_fraction=0.0),
)

strategy = Strategy(
    name='s_proc_fail',
    data=DataConfig(source='parquet://THIS_FILE_DOES_NOT_EXIST.parquet', calendar='XNYS', frequency='1d', start='2025-01-01', end='2025-01-07'),
    universe=Universe(name='TEST', static_instruments=['AAPL']),
    factors=factors,
    signals=signals,
    portfolio=portfolio,
    execution=execution,
    costs=costs,
    backtest=BacktestConfig(engine='event_driven', reporting=Reporting(output_dir=None)),
)
"""
    (strategies_dir / "s_proc_fail.py").write_text(src, encoding="utf-8")

    app = create_app()

    from quantdsl_backtest.platform_api.services.task_runner import TaskRunner

    app.state.task_runner = TaskRunner(run_store=app.state.run_store, enable_process_pool=True, max_workers=1)

    client = TestClient(app, raise_server_exceptions=False)

    r = client.post("/api/runs", json={"strategy_id": "s_proc_fail", "params": {}})
    assert r.status_code == 200
    run_id = r.json()["run_id"]

    run = _poll_run_terminal(client, run_id, timeout_s=30.0)
    assert run["status"] == "failed"
    assert run.get("error")

    import pathlib

    out_dir = pathlib.Path(run["artifacts_dir"])
    assert (out_dir / "logs.txt").exists()
    txt = (out_dir / "logs.txt").read_text(encoding="utf-8", errors="replace")
    assert ("Exception" in txt) or ("Traceback" in txt)
